
SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_ID NOT IN (SELECT CAR_ID 
                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
AND A.CAR_TYPE IN ('세단', 'SUV')
AND C.DURATION_TYPE = '30일 이상'
AND FLOOR(A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE/100)) BETWEEN 500000 AND 2000000
ORDER BY FLOOR(A.DAILY_FEE * 30 * (1 - C.DISCOUNT_RATE/100)) DESC, A.CAR_TYPE, A.CAR_ID DESC;