SELECT
    YEAR(A.DIFFERENTIATION_DATE) AS YEAR,
    (B.max_size - A.SIZE_OF_COLONY) AS YEAR_DEV,
    A.ID
FROM ECOLI_DATA A
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS year,
        MAX(SIZE_OF_COLONY) AS max_size
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B.year
ORDER BY YEAR, YEAR_DEV;